#!/bin/bash
#usage : ./go fichier.cpp [autres.cpp ...]

#stoppe le script à la première erreur
set -e

#le nom du programme = nom du premier fichier, sans le .cpp
programme="${1%.cpp}"

#compile avec avertissements, infos de débogage, standard C++20
g++ -std=c++20 -Wall -Wextra -g "$@" -o "$programme"

#lance le programme
./"$programme"
